apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: staging
 
namePrefix: staging-
 
bases:
  - ../../base
 
patchesStrategicMerge:
  - replica-patch.yaml
 
commonLabels:
  environment: staging
